src/Entity/Medias.php
<?php

namespace App\Entity;

use App\Repository\MediasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MediasRepository::class)]
class Medias
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $path = null;

    #[ORM\Column]
    private ?int $width = 1;

    #[ORM\Column]
    private ?int $height = 1;

    #[ORM\Column]
    private ?bool $is_active = true;

    #[ORM\ManyToOne(inversedBy: 'medias')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $category = null;

    #[ORM\ManyToOne(inversedBy: 'medias')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(int $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\MediasRepository;
use App\Repository\CategoriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
  #[Route('/', name: 'app_home')]
  public function index(Request $request, MediasRepository $mediasRepository, CategoriesRepository $categoriesRepository): Response
  {
    if ($request->isMethod('post') && intval($request->get('category_filter'), 10) !== 0) {
      $mediaSelected = $request->get('category_filter');
      $medias = $mediasRepository->findBy(
        array(
          'category' => $request->get('category_filter'),
          'is_active' => true
        ),
        array('id' => 'DESC')
      );
    } else {
      $mediaSelected = 0;
      $medias = $mediasRepository->findBy(
        array('is_active' => true),
        array('id' => 'DESC')
      );
    }

    $categories = $categoriesRepository->findAll();

    return $this->render('home/index.html.twig', [
      'user' => $this->getUser(),
      'medias' => $medias,
      'mediaSelected' => $mediaSelected,
      'categories' => $categories,
    ]);
  }

  #[Route('/posts/{id}', name: 'app_posts')]
  public function userPost($id, Request $request, MediasRepository $mediasRepository, CategoriesRepository $categoriesRepository): Response
  {
    if ($request->isMethod('post') && intval($request->get('category_filter'), 10) !== 0) {
      $mediaSelected = $request->get('category_filter');
      $medias = $mediasRepository->findBy(
        array(
          'user' => $id,
          'category' => $request->get('category_filter'),
          'is_active' => true
        ),
        array('id' => 'DESC'),
      );
    } else {
      $mediaSelected = 0;
      $medias = $mediasRepository->findBy(
        array(
          'user' => $id,
          'is_active' => true
        ),
        array('id' => 'DESC'),
      );
    }

    $categories = $categoriesRepository->findAll();

    return $this->render('home/index.html.twig', [
      'user' => $this->getUser(),
      'medias' => $medias,
      'mediaSelected' => $mediaSelected,
      'categories' => $categories,
    ]);
  }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vignettes | Dashboard{% endblock %}

{% block css %}
<style>
    .col-span-1 {
        grid-column: span 1 / span 1;
    }
    .col-span-2 {
        grid-column: span 2 / span 2;
    }
    .row-span-1 {
        grid-row: span 1 / span 1;
    }
    .row-span-2 {
        grid-row: span 2 / span 2;
    }
</style>
{% endblock %}

{% block body %}
    <section class="py-4 px-8 md:px-14 lg:py-16 lg:px-20">
        <div class="flex flex-col gap-2 items-center mb-16">
            <p class="font-semibold">Filtres</p>
            <form method="post" id="filterForm">
                <label for="categories">Catégories :</label>
                <select id="categories" name="category_filter">
                    <option value="0">----- Aucun -----</option>
                    {% for category in categories %}
                        <option {{ mediaSelected == category.id ? 'selected' : '' }} value="{{ category.id }}">{{ category.label }}</option>
                    {% endfor %}
                </select>
            </form>
        </div>

        <div class="w-full grid grid-cols-[repeat(2,minmax(150px,150px))] md:grid-cols-[repeat(4,minmax(150px,200px))] lg:grid-cols-[repeat(6,minmax(200px,200px))] grid-rows-[auto,minmax(200px,200px)] gap-5">
            {% for media in medias %}
                <div
                    id="modal-media-{{ media.id }}"
                    class="modal-media bg-gray-300 w-[{{ media.width > 1 ? '420' : '200' }}px] h-[{{ media.height > 1 ? '420' : '200' }}px] col-span-{{ media.width }} row-span-{{ media.height }} flex justify-center items-center rounded-lg overflow-hidden cursor-pointer"
                >
                    <img
                        src="{{ 'mp3' in media.path ? asset('icons/music.svg') : asset('img/uploads/') ~ media.path }}"
                        class="{{ 'mp3' in media.path ? 'w-20 h-20' : 'w-full' }}"
                    />
                </div>
            {% endfor %}
        </div>
    </section>

    {% include 'home/modal.html.twig' %}
{% endblock %}

{% block scripts %}
<script>
    const modalMedia = document.querySelectorAll('.modal-media');
    const modalBgClose = document.querySelectorAll('.bg-close-modal');
    const modalClose = document.querySelectorAll('.close-modal');

    for (let i = 0; i < {{ medias|length }}; i++) {
        const modal = document.querySelector('.' + modalMedia[i].id);

        modalMedia[i].addEventListener('click', () => { modal.style.display = "flex"; });
        modalBgClose[i].addEventListener('click', () => { modal.style.display = "none"; });
        modalClose[i].addEventListener('click', () => { modal.style.display = "none"; });
    }

    {% if app.user %}
        {% if 'ROLE_ADMIN' in user.roles %}
            const modalEditMedia = document.querySelectorAll('.modal-edit-media');
            const modalBgCloseEdit = document.querySelectorAll('.bg-close-edit-modal');
            const modalCloseEdit = document.querySelectorAll('.close-edit-modal');

            for (let i = 0; i < {{ medias|length }}; i++) {
                const modalEdit = document.querySelector('.' + modalEditMedia[i].id);

                modalEditMedia[i].addEventListener('click', () => { modalEdit.style.display = "flex"; });
                modalBgCloseEdit[i].addEventListener('click', () => { modalEdit.style.display = "none"; });
                modalCloseEdit[i].addEventListener('click', () => { modalEdit.style.display = "none"; });
            }
        {% endif %}
    {% endif %}

    const form = document.getElementById('filterForm');
    const select = document.getElementById('categories');

    select.addEventListener('change', () => {
        form.submit();
    });
</script>
{% endblock %}

templates/home/modal.html.twig
{% for media in medias %}
    <div class="modal-media-{{ media.id }} absolute top-0 bottom-0 right-0 left-0 justify-center items-center z-10" style="display: none;">
        <div id="bg-close-modal-{{ media.id }}" class="bg-close-modal absolute w-full h-full bg-black opacity-20 z-20"></div>
        <div class="bg-white opacity-1 z-30 p-16 rounded-3xl flex flex-col gap-6 max-w-[800px]">
            <div class="flex justify-center">
                <audio controls src="{{ asset('img/uploads/') ~ media.path }}" class="{{ 'mp3' in media.path ? 'w-full' : 'hidden' }}"></audio>
                <img
                    src="{{ asset('img/uploads/') ~ media.path }}"
                    class="{{ 'mp3' in media.path ? 'hidden' : '' }} {{ media.width > media.height ? 'w-[600px]' : 'h-[400px]' }}"
                />
            </div>

            <div class="flex justify-between gap-8">
                <div>
                    <span class="font-semibold">TITRE : </span>
                    <span>{{ media.title }}</span>
                </div>
                <div>
                    <span class="font-semibold">CATÉGORIE : </span>
                    <span>{{ media.category.label }}</span>
                </div>
                <div>
                    <span class="font-semibold">NUMÉRO : </span>
                    <a href="{{ path('app_posts', { 'id': media.user.id }) }}">{{ media.user.id }}</a>
                </div>
            </div>

            <div>
                <span class="font-semibold mb-3">DESCRIPTION :</span>
                <p>{{ media.description }}</p>
            </div>

            <div class="flex justify-end gap-6">
                {% if app.user %}
                    {% if 'ROLE_ADMIN' in user.roles %}
                        <div id="modal-edit-media-{{ media.id }}" class="modal-edit-media flex gap-2 cursor-pointer">
                            <img src="{{ asset('icons/edit.svg') }}" />
                            <span>Modifier</span>
                        </div>
                        <div class="flex gap-2 cursor-pointer">
                            <img src="{{ asset('icons/trash.svg') }}" />
                            <span>Supprimer</span>
                        </div>
                    {% endif %}
                {% endif %}
                <div class="flex gap-2 cursor-pointer">
                    <img src="{{ asset('icons/add.svg') }}" class="rotate-45" />
                    <span id="close-modal-{{ media.id }}" class="close-modal">Fermer</span>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-edit-media-{{ media.id }} absolute top-0 bottom-0 right-0 left-0 justify-center items-center z-10" style="display: none;">
        <div id="bg-close-edit-modal-{{ media.id }}" class="bg-close-edit-modal absolute w-full h-full bg-black opacity-20 z-20"></div>
        <div class="bg-white opacity-1 z-30 p-12 rounded-3xl flex flex-col gap-6 max-w-[800px]">
            <h2 class="font-semibold text-xl">Modifier le média</h2>

            <form action="{{ path('update_media', { 'id': media.id }) }}" method="post" class="flex flex-col gap-4 w-[350px]">
                <label class="relative inline-flex items-center cursor-pointer">
                    <input type="checkbox" name="is_active" class="sr-only peer" {{ media.isActive ? 'checked' : '' }}>
                    <div class="w-11 h-6 bg-gray-200 rounded-full dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
                    <span class="ml-3 text-sm font-medium text-gray-900 dark:text-gray-300">Afficher le média</span>
                </label>

                <div class="flex items-center gap-2">
                    <label for="" class="whitespace-nowrap">Largeur : </label>
                    <input type="number" name="width" placeholder="Largeur" min="1" max="2" value="{{ media.width }}" class="w-full py-2 px-4 bg-gray-300 rounded-xl" />
                </div>

                <div class="flex items-center gap-2">
                    <label for="" class="whitespace-nowrap">Hauteur : </label>
                    <input type="number" name="height" placeholder="Hauteur" min="1" max="2" value="{{ media.height }}" class="w-full py-2 px-4 bg-gray-300 rounded-xl" />
                </div>

                <div class="flex gap-4">
                    <span id="close-edit-modal-{{ media.id }}" class="close-edit-modal text-center border border-2 border-gray-600 p-2 w-full rounded-xl cursor-pointer">Annuler</span>
                    <button type="submit" class="bg-gray-600 text-white p-2 w-full rounded-xl">
                        Modifier
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endfor %}